### PR TITLE
Max Beneficiaries Warning

### LINKED ISSUE #345: limit number of beneficiaries reached returns wrong message
If a community has a limit of 50, when trying to add more it says the wallet address is invalid when it should say something like "Limit of beneficiaries has been reached".

### PR DESCRIPTION
**Pull request by hugomarquesdev**
This PR fixes #345 

## Changes

- Shows a message when the limit of beneficiaries is reached and doesn't allow to add more.

## Tests

- [x] Tested on mobile
- [x] Tested on dektop

This PR should be manually tested by @obernardovieira @PauloSousapt , included on reviewers.

### CODE REVIEW

**Review by obernardovieira — CHANGES_REQUESTED** [review]
With Manager 5 demo account, trying to add beneficiary, I've got A "User not found. Please enter a valid Wallet Address." But on console I see I've reached the max beneficiaries

File: src/views/Beneficiaries/index.tsx [hunk 1]
```diff
@@ -117,18 +121,18 @@ const Beneficiaries: React.FC<{ isLoading?: boolean }> = props => {
                     <Tabs defaultIndex={+getByKey('state')}>
                         <TabList>
                             <Tab
-                                number={data?.beneficiaryEntities?.filter((elem: any) => elem.state === 0)?.length}
-                                onClick={() => update({ 'page': 0, 'state': 0})}
+                                number={beneficiariesStateLength(0)}
+                                onClick={() => update('state', 0)}
```
Comment (PauloSousapt) [inline src/views/Beneficiaries/index.tsx:125]: Don't remove the reset of the page, otherwise when changing between tabs the page won't change, and then if we have 10 pages on tab 0, and only 1 in tab 2, if we are on page 5 in tab 0 and we change to the tab 1, we'll stay in the page 5 which as no results. Whenever we change the tab we need to ensure we go to the first page of that tab.
