### PR TITLE
Dogfooding Fixes

### LINKED ISSUE #241: df issues batch 3
# Hugo

- [x] * In community page, there are 2 email icons. It should be an email icon and a phone icon
- [x] * In Notifications, the link of each notification should be directly “connected” to the notification.
- [x] * In contribute, the message after approving/contributing cUSD is only “success”. It should be capitalized or even change the message.
- [x] * When there’s no wallet connected the logo link does nothing

# Paulo Soares

- [x] * After log in the user should be redirected to his dashboard

# Paulo Sousa

- [x] * In community details, promoter social icons not found and components style is broken
- [x] * On mobile communities page, we have a outer scroll and 2 connect wallet buttons - see "navigation side - mobile" on design to fix

# João

- [x] * Filter by country showing countries that dont have accepted communities (to solve use "status=valid" /communities/count?groupBy=country&status=valid)

# Bernardo

- [x] * When the user has no communities, values should default to zero
- [x] * Communities with zero beneficiaries should show the card anyways with zero there (on community page)
- [x] * increment interval on proposals description is wrong. See proposal #26. Should be 5 minutes. It's missing the blocks number division, needs to be divided by 12, like on community page

### PR DESCRIPTION
**Pull request by hugomarquesdev**
This PR fixes #241 

## Tests

- [x] Tested on mobile
- [x] Tested on dektop

This PR should be manually tested by @PauloSousapt, included on reviewers.

### CODE REVIEW

**Review by obernardovieira — COMMENTED** [review]
To make this like the design, very clean and good looking, I suggest using a regex. If there's a match, render de match, if not, render the full url.

My suggested [regex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match): `https:\/\/(?:www.)?(?:twitter|instagram|facebook)\.com\/([\w\d._-]*)`

you can try it here https://regex101.com/ using the links from one of the communities (ones below, for example)
```
https://twitter.com/rio__global
https://refugeeintegration.org/
https://www.instagram.com/rio.global/
https://www.facebook.com/Refugee-Integ__ration-Organisation-133071127335606/
```

**Comment by PauloSousapt** [comment]
@hugomarquesdev I believe the social icons still need further styling, the icons don't match with the designs and there are some adjustments that probably will need to be made, i don't think this will pass design review as it is. Maybe it's better to check with design the current layout, so it can be adapted to real use cases like we have in staging.

Plus, all the prismic data in this view as disappeared.

File: src/components/SocialLink.tsx [hunk 1]
```diff
@@ -10,12 +10,13 @@ interface SocialMedia {
```
Comment (PauloSousapt) [inline src/components/SocialLink.tsx:10]: @hugomarquesdev I believe the social icons still need further styling, the icons don't match with the designs and there are some adjustments that probably will need to be made, i don't think this will pass design review as it is. Maybe it's better to check with design the current layout, so it can be adapted to real use cases like we have in staging.

Plus, all the prismic data in this view as disappeared.

Apart from that, everything seems fine, tested mobile and desktop.

**Review by PauloSousapt — CHANGES_REQUESTED** [review]
It needs some adjustments coordinated with design.

File: src/components/SocialLink.tsx (hunk 1 above)
Comment (hugomarquesdev) [reply src/components/SocialLink.tsx:10]: @PauloSousapt 

The icons are the same as the website and storybook (impactMarket design system). The phone icon was directly downloaded from figma with paulo soares. I also noticed that they seem different in the app and figma but I don't know why exactly...

I'll check the prismic data.

Comment (hugomarquesdev) [reply src/components/SocialLink.tsx:10]: > Plus, all the prismic data in this view as disappeared.

In which view? Community?

**Review by PauloSousapt — APPROVED** [review]

**Review by obernardovieira — APPROVED** [review]
